"""phase_2_complete_schema

Revision ID: e9e3c6b4b191
Revises: 
Create Date: 2025-10-22 13:26:26.217118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9e3c6b4b191'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addons',
    sa.Column('addon_type', sa.Enum('verification', 'visibility_boost', 'intro_package', 'other', name='addon_type_enum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addons_addon_type'), 'addons', ['addon_type'], unique=False)
    op.create_index(op.f('ix_addons_id'), 'addons', ['id'], unique=False)
    op.create_index(op.f('ix_addons_is_active'), 'addons', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('developer', 'investor', 'agency', 'buyer', 'admin', name='user_role_enum'), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('subscription_status', sa.Enum('active', 'expired', 'trial', 'none', name='subscription_status_enum'), server_default='none', nullable=False),
    sa.Column('subscription_expiry', sa.DateTime(), nullable=True),
    sa.Column('verified_status', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('accepted_non_circumvention', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('non_circumvention_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('tos_version_accepted', sa.String(length=20), nullable=True),
    sa.Column('ip_registered', sa.String(length=45), nullable=True),
    sa.Column('success_fee_policy_version', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tier'), 'users', ['tier'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agency_listings',
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('size_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('access_level', sa.Enum('public', 'verified_only', 'pre_launch', name='access_level_enum'), server_default='public', nullable=False),
    sa.Column('contact_visibility', sa.Enum('hidden', 'proxy', 'revealed', name='contact_visibility_enum'), server_default='hidden', nullable=False),
    sa.Column('visibility_score', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='project_status_enum'), server_default='draft', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agency_listings_agency_id'), 'agency_listings', ['agency_id'], unique=False)
    op.create_index(op.f('ix_agency_listings_city'), 'agency_listings', ['city'], unique=False)
    op.create_index(op.f('ix_agency_listings_country'), 'agency_listings', ['country'], unique=False)
    op.create_index(op.f('ix_agency_listings_id'), 'agency_listings', ['id'], unique=False)
    op.create_index(op.f('ix_agency_listings_property_type'), 'agency_listings', ['property_type'], unique=False)
    op.create_index(op.f('ix_agency_listings_status'), 'agency_listings', ['status'], unique=False)
    op.create_index(op.f('ix_agency_listings_visibility_score'), 'agency_listings', ['visibility_score'], unique=False)
    op.create_table('api_request_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('request_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_request_logs_created_at'), 'api_request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_request_logs_endpoint'), 'api_request_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_request_logs_id'), 'api_request_logs', ['id'], unique=False)
    op.create_index(op.f('ix_api_request_logs_ip_address'), 'api_request_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_api_request_logs_user_id'), 'api_request_logs', ['user_id'], unique=False)
    op.create_table('buyer_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('investment_capacity', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_buyer_profiles_user_id')
    )
    op.create_index(op.f('ix_buyer_profiles_id'), 'buyer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_buyer_profiles_user_id'), 'buyer_profiles', ['user_id'], unique=True)
    op.create_table('projects',
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('total_investment_required', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('roi_estimate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('size_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('access_level', sa.Enum('public', 'verified_only', 'pre_launch', name='access_level_enum'), server_default='public', nullable=False),
    sa.Column('contact_visibility', sa.Enum('hidden', 'proxy', 'revealed', name='contact_visibility_enum'), server_default='hidden', nullable=False),
    sa.Column('visibility_score', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='project_status_enum'), server_default='draft', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_city'), 'projects', ['city'], unique=False)
    op.create_index(op.f('ix_projects_country'), 'projects', ['country'], unique=False)
    op.create_index(op.f('ix_projects_developer_id'), 'projects', ['developer_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_property_type'), 'projects', ['property_type'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_visibility_score'), 'projects', ['visibility_score'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', 'trial', name='subscription_record_status_enum'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('grace_period_ends', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_expiry_date'), 'subscriptions', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('user_addons',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'expired', 'cancelled', name='addon_status_enum'), server_default='pending', nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['addons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addons_addon_id'), 'user_addons', ['addon_id'], unique=False)
    op.create_index(op.f('ix_user_addons_id'), 'user_addons', ['id'], unique=False)
    op.create_index(op.f('ix_user_addons_status'), 'user_addons', ['status'], unique=False)
    op.create_index(op.f('ix_user_addons_user_id'), 'user_addons', ['user_id'], unique=False)
    op.create_table('leads',
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('chat', 'email_proxy', 'platform', 'direct', name='lead_channel_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'contacted', 'responded', 'closed', name='lead_status_enum'), server_default='pending', nullable=False),
    sa.Column('first_contact_ip', sa.String(length=45), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['agency_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_initiator_id'), 'leads', ['initiator_id'], unique=False)
    op.create_index(op.f('ix_leads_listing_id'), 'leads', ['listing_id'], unique=False)
    op.create_index(op.f('ix_leads_project_id'), 'leads', ['project_id'], unique=False)
    op.create_index(op.f('ix_leads_recipient_id'), 'leads', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('matches',
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'contacted', 'closed', name='match_status_enum'), server_default='pending', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_developer_id'), 'matches', ['developer_id'], unique=False)
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_investor_id'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('ix_matches_project_id'), 'matches', ['project_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('project_addons',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'expired', 'cancelled', name='addon_status_enum'), server_default='pending', nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('visibility_boost_amount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['addons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_addons_addon_id'), 'project_addons', ['addon_id'], unique=False)
    op.create_index(op.f('ix_project_addons_id'), 'project_addons', ['id'], unique=False)
    op.create_index(op.f('ix_project_addons_project_id'), 'project_addons', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_addons_status'), 'project_addons', ['status'], unique=False)
    op.create_table('project_documents',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('teaser', 'IM', 'financial_model', 'permit', 'render_pdf', 'other', name='doc_type_enum'), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('access_level', sa.Enum('public', 'verified_only', 'pre_launch', name='access_level_enum'), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_documents_id'), 'project_documents', ['id'], unique=False)
    op.create_index(op.f('ix_project_documents_project_id'), 'project_documents', ['project_id'], unique=False)
    op.create_table('deals',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('deal_type', sa.Enum('capital_raise', 'asset_sale', 'agency_referral', name='deal_type_enum'), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('success_fee_rate_locked', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('success_fee_calculated', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('success_fee_minimum', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('locked_tier', sa.String(length=50), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'paid', 'disputed', name='deal_status_enum'), server_default='pending', nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('payment_received_at', sa.DateTime(), nullable=True),
    sa.Column('disputed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_lead_id'), 'deals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_table('lead_channels',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.Enum('email_proxy', 'chat', 'direct', name='channel_type_enum'), nullable=False),
    sa.Column('proxy_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_channels_id'), 'lead_channels', ['id'], unique=False)
    op.create_index(op.f('ix_lead_channels_lead_id'), 'lead_channels', ['lead_id'], unique=False)
    op.create_table('messages',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_lead_id'), 'messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('deal_tranches',
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('tranche_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('fx_rate_to_eur', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('amount_eur_cached', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_tranches_deal_id'), 'deal_tranches', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_tranches_id'), 'deal_tranches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deal_tranches_id'), table_name='deal_tranches')
    op.drop_index(op.f('ix_deal_tranches_deal_id'), table_name='deal_tranches')
    op.drop_table('deal_tranches')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_lead_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_lead_channels_lead_id'), table_name='lead_channels')
    op.drop_index(op.f('ix_lead_channels_id'), table_name='lead_channels')
    op.drop_table('lead_channels')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_index(op.f('ix_deals_lead_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_project_documents_project_id'), table_name='project_documents')
    op.drop_index(op.f('ix_project_documents_id'), table_name='project_documents')
    op.drop_table('project_documents')
    op.drop_index(op.f('ix_project_addons_status'), table_name='project_addons')
    op.drop_index(op.f('ix_project_addons_project_id'), table_name='project_addons')
    op.drop_index(op.f('ix_project_addons_id'), table_name='project_addons')
    op.drop_index(op.f('ix_project_addons_addon_id'), table_name='project_addons')
    op.drop_table('project_addons')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_project_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_investor_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_developer_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_recipient_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_project_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_listing_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_initiator_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_user_addons_user_id'), table_name='user_addons')
    op.drop_index(op.f('ix_user_addons_status'), table_name='user_addons')
    op.drop_index(op.f('ix_user_addons_id'), table_name='user_addons')
    op.drop_index(op.f('ix_user_addons_addon_id'), table_name='user_addons')
    op.drop_table('user_addons')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expiry_date'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_projects_visibility_score'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_property_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_developer_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_country'), table_name='projects')
    op.drop_index(op.f('ix_projects_city'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_buyer_profiles_user_id'), table_name='buyer_profiles')
    op.drop_index(op.f('ix_buyer_profiles_id'), table_name='buyer_profiles')
    op.drop_table('buyer_profiles')
    op.drop_index(op.f('ix_api_request_logs_user_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_ip_address'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_endpoint'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_created_at'), table_name='api_request_logs')
    op.drop_table('api_request_logs')
    op.drop_index(op.f('ix_agency_listings_visibility_score'), table_name='agency_listings')
    op.drop_index(op.f('ix_agency_listings_status'), table_name='agency_listings')
    op.drop_index(op.f('ix_agency_listings_property_type'), table_name='agency_listings')
    op.drop_index(op.f('ix_agency_listings_id'), table_name='agency_listings')
    op.drop_index(op.f('ix_agency_listings_country'), table_name='agency_listings')
    op.drop_index(op.f('ix_agency_listings_city'), table_name='agency_listings')
    op.drop_index(op.f('ix_agency_listings_agency_id'), table_name='agency_listings')
    op.drop_table('agency_listings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tier'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_addons_is_active'), table_name='addons')
    op.drop_index(op.f('ix_addons_id'), table_name='addons')
    op.drop_index(op.f('ix_addons_addon_type'), table_name='addons')
    op.drop_table('addons')
    # ### end Alembic commands ###
